In [262]:
import numpy as np

There is 20 training example and each has 5 features

**Note:** Here randomly values are choosen. It is only for implementation

In [263]:
number_of_features = 5
number_of_examples = 20

first_column = np.ones((number_of_examples, 1))

X = np.random.randint(1, 101, size=(number_of_examples, number_of_features))
print(X)

X = np.concatenate((first_column, X), axis=1)
print(X.shape)
Y = np.random.randint(1, 101, size=number_of_examples)


[[ 83  27  55  16   1]
 [ 23  95  67  55  41]
 [ 62  91  86  13  93]
 [ 29  32  45   1  60]
 [  6  60  53  40  26]
 [ 24  44  85  56 100]
 [  2  17  57  82  92]
 [ 31  44  11  60  79]
 [ 79  52  52  37  54]
 [ 77  17  58  22  90]
 [ 18  46  75  43  93]
 [  6  77  18  58  54]
 [ 40  39  43  38  71]
 [ 51  70  45  73   1]
 [ 21  37  99  30  57]
 [ 23  34  68   4  79]
 [  7  18  12  37  11]
 [ 63  18 100  53  95]
 [ 30  99  59  34   1]
 [ 62  76  71  23  24]]
(20, 6)


In [ ]:
X_T = np.transpose(X)

W = X_T @ X
W = np.linalg.inv(W)    
W = W @ X_T

W = W @ Y

print(W)

[ 8.13255021e+01 -1.27512750e-01 -3.87666555e-01 -3.17312034e-01
 -1.14716982e-01  8.11854298e-02]
[ 8.13255021e+01 -1.27512750e-01 -3.87666555e-01 -3.17312034e-01
 -1.14716982e-01  8.11854298e-02]


In [ ]:
prediction = X @ W

prediction


[19  4 32 79  7 47 59 19 36 75 22 64 76 45 79  5 79  8 11 16]
[41.06849873 17.32364845 16.91214438 55.69966988 38.00503639 35.93073678
 54.45562624 56.35547609 34.7325931  51.29550604 40.01662327 42.7289125
 48.8664992  25.11349721 34.0762405  49.58960871 66.29568185 36.21561326
 16.58052869 20.73785874]
