# 34. Write a simple CNN model definition using Keras.

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models, datasets
import numpy as np

In [2]:
df = datasets.cifar10
type(df)

module

In [3]:
(x_train, y_train), (x_test, y_test) = df.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [4]:
type(x_train),x_train.shape

(numpy.ndarray, (50000, 32, 32, 3))

In [5]:
x_train[0][0] # 1st row of 2D grid contains 32 RGB

array([[ 59,  62,  63],
       [ 43,  46,  45],
       [ 50,  48,  43],
       [ 68,  54,  42],
       [ 98,  73,  52],
       [119,  91,  63],
       [139, 107,  75],
       [145, 110,  80],
       [149, 117,  89],
       [149, 120,  93],
       [131, 103,  77],
       [125,  99,  76],
       [142, 115,  91],
       [144, 112,  86],
       [137, 105,  79],
       [129,  97,  71],
       [137, 106,  79],
       [134, 106,  76],
       [124,  97,  64],
       [139, 113,  78],
       [139, 112,  75],
       [133, 105,  69],
       [136, 105,  74],
       [139, 108,  77],
       [152, 120,  89],
       [163, 131, 100],
       [168, 136, 108],
       [159, 129, 102],
       [158, 130, 104],
       [158, 132, 108],
       [152, 125, 102],
       [148, 124, 103]], dtype=uint8)

In [6]:
x_train[0][0][1] # The 2nd pixel RGB

array([43, 46, 45], dtype=uint8)

In [7]:
unique_elements = np.unique(y_train)
unique_elements,np.unique(y_test)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8))

In [8]:
y_train[:5] # 2D array -> [ [a], [b], ..., [z..zz] ]

array([[6],
       [9],
       [9],
       [4],
       [1]], dtype=uint8)

In [9]:
y_train = y_train.reshape(-1,)  # Make 1D array -> [a, b, ..., z...z]
y_test = y_test.reshape(-1,)

In [10]:
y_train[:5]

array([6, 9, 9, 4, 1], dtype=uint8)

In [11]:
classes = ['airplane','automobile','bird','cat','deer',
           'dog','frog','horse','ship','truck']

In [12]:
x_train = x_train/255 # Dividing by 255 normalizes the values to the range 0 to 1
x_test = x_test/255   # normalized_pixel=pixel_value/255

### CNN Model

In [13]:
cnn = models.Sequential([])

In [14]:
cnn = models.Sequential([
    layers.Conv2D(filters = 32, kernel_size=(3,3), activation = 'relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(filters = 64, kernel_size=(3,3), activation = 'relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(64, activation = 'relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(10, activation = 'softmax')

])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
cnn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 30, 30, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 15, 15, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 13, 13, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │       147,520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 169,322 (661.41 KB)

 Trainable params: 169,322 (661.41 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
cnn.compile(loss = 'sparse_categorical_crossentropy',
            optimizer = 'rmsprop',
            metrics = ['Accuracy'])

In [17]:
cnn.fit(x_train, y_train, batch_size=64, epochs = 5)

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 57s 71ms/step - Accuracy: 0.3063 - loss: 1.8939
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 84s 74ms/step - Accuracy: 0.5438 - loss: 1.2938
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 79s 70ms/step - Accuracy: 0.6161 - loss: 1.0904
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 81s 69ms/step - Accuracy: 0.6664 - loss: 0.9669
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 55s 70ms/step - Accuracy: 0.7000 - loss: 0.8630


In [18]:
cnn.evaluate(x_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - Accuracy: 0.6224 - loss: 1.0574


[1.0729515552520752, 0.6193000078201294]

In [19]:
y_pred = cnn.predict(x_test)
y_pred = [np.argmax(i) for i in y_pred]
y_pred[:5]

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step


[np.int64(3), np.int64(8), np.int64(8), np.int64(8), np.int64(4)]

In [20]:
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)