### **Simple Neural Network (Forward Propagation) Using NumPy**

In [1]:
import numpy as np

In [2]:
X = np.array([[185.32, 12.69],
 [259.92, 11.87],
 [231.01, 14.41],
 [175.37, 11.72],
 [187.12, 14.13],
 [225.91, 12.1 ],
 [208.41, 14.18],
 [207.08, 14.03],
 [280.6, 14.23],
 [202.87, 12.25],
 [196.7, 13.54],
 [270.31, 14.6 ],
 [192.95, 15.2 ],
 [213.57, 14.28],
 [164.47, 11.92],
 ])



Y = np.array([[1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [1.],
 [1.],
 [0.],
 [0.],
 [0.],
 [0.],

 ])

print(X.shape,Y.shape)

(15, 2) (15, 1)


<img src="images/nural_net_layer.png" width="800" height="350">

#### Scaling/Normalization
```StandardScaler().scaler.fit_transform(X)```

It scales each feature (column) so that:

Mean = 0

Standard deviation = 1

X_standardized = (X - X_mean) / X_std


In [3]:
from sklearn.preprocessing import StandardScaler
# Initialize the StandardScaler
scaler = StandardScaler()
print(X[:5])

# Fit the scaler to your data and transform it
X_standardized = scaler.fit_transform(X)

print(X_standardized[:5])

[[185.32  12.69]
 [259.92  11.87]
 [231.01  14.41]
 [175.37  11.72]
 [187.12  14.13]]
[[-0.84588115 -0.63002953]
 [ 1.39811736 -1.34756317]
 [ 0.52849273  0.87504102]
 [-1.14518122 -1.47881932]
 [-0.79173642  0.63002953]]


##### Sigmoid Activation Function

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

<img src="images/forward_prop.png" width="800" height="350">

In [5]:
# dense layer:  A set of weights and bias
def dense(a_in,W,b):
    units=W.shape[1] # units are the nurons of a layer. Here  W[number_of_feature_a_in][number_of_units]

    a_out=np.zeros(units)

    for j in range(units):
        w=W[:,j]
        z=np.dot(a_in,w)+b[j] # a will dor with each units
        a_out[j] = sigmoid(z)

    return a_out

#### dense function using numpy **'matmul'** (matrix-multiplication function)

In [6]:
def dense_matmul(X,W,b):
    z = np.matmul(X,W) + b
    a_out = sigmoid(z)
    return a_out

#### For 1-hidden layer
<img src="images/single_layer_nn.png" width="800" height="800">

In [7]:
W_tmp = [np.array([[-8.93,  0.29, 12.9 ], 
                   [-0.1,  -7.32, 10.81]]),  # 3 units, 2 weights for 2 features # layer-1

         np.array([[-31.18], 
                   [-27.59], 
                   [-32.56]])]  # 1 units, 3 weights for 3 features # layer-2 (output layer)


b_tmp = [np.array([-9.82, -9.28,  0.96]),  # 3 unit # layer-1
         np.array([15.41])]               # 1 unit # layer-2 (output layer)


In [8]:
def sequential(x, W, b):
    layers=len(W)
    a = x
    for layer in range(layers):
        a = dense(a, W[layer], b[layer])
    return a


#### Predictions

In [9]:
def my_predict(X, W, b):
    m = X.shape[0]
    p = np.zeros((m,1))
    for i in range(m):
        p[i,0] = 0 if sequential(X[i], W, b)<0.5 else 1
    return(p)

In [10]:
prediction=my_predict(X_standardized,W_tmp,b_tmp)

print(prediction)

for i in range(len(Y)):
    print(Y[i]==prediction[i])

[[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
[ True]
