### **Regression**

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
data = np.array([[1651., 432.65],
  [1691.82, 454.94],
  [1732.63, 471.53],
  [1773.45, 482.51],
  [1814.27, 468.36],
  [1855.08, 482.15],
  [1895.9, 540.02],
  [1936.71, 534.58],
  [1977.53, 558.35],
  [2018.35, 566.42],
  [2059.16, 581.4 ],
  [2099.98, 596.46],
  [2140.8, 596.71],
  [2181.61, 619.45],
  [2222.43, 616.58],
  [2263.24, 653.16],
  [2304.06, 666.52],
  [2344.88, 670.59],
  [2385.69, 669.02],
  [2426.51, 678.91],
  [2467.33, 707.44],
  [2508.14, 710.76],
  [2548.96, 745.19],
  [2589.78, 729.85],
  [2630.59, 743.8 ],
  [2671.41, 738.2 ],
  [2712.22, 772.95],
  [2753.04, 772.22],
  [2793.86, 784.21],
  [2834.67, 776.43],
  [2875.49, 804.78],
  [2916.31, 833.27],
  [2957.12, 825.69],
  [2997.94, 821.05],
  [3038.76, 833.82],
  [3079.57, 833.06],
  [3120.39, 825.7 ],
  [3161.2, 843.58],
  [3202.02, 869.4 ],
  [3242.84, 851.5 ],
  [3283.65, 863.18],
  [3324.47, 853.01],
  [3365.29, 877.16],
  [3406.1, 863.74],
  [3446.92, 874.67],
  [3487.73, 877.74],
  [3528.55, 874.11],
  [3569.37, 882.8 ],
  [3610.18, 910.83],
  [3651., 897.42]])




**Input variable ```x``` contains 50 traing example. Each example has 1 feature**<br>
**Output variable ```y``` contains 50 corresponding output.**

In [3]:
# Split the inputs and outputs into separate arrays
x = data[:,0]
y = data[:,1]
print(x.shape,y.shape)

# Convert 1-D arrays into 2-D because the commands later will require it
x = np.expand_dims(x, axis=1)
y = np.expand_dims(y, axis=1)

(50,) (50,)


#### **Split the dataset into training, cross validation, and test sets (60%, 40%, 40%)**

In [4]:
# Geting 60% of the dataset as the training set. Putting the remaining 40% in temporary variables: x_ and y_.
'''
random_state=1: -> train_test_split shuffles the data randomly before splitting it. 
                -> If you don't set random_state, 
'''
x_train, x_, y_train, y_ = train_test_split(x, y, test_size=0.40, random_state=1) 
# x_train, x_, y_train, y_ = train_test_split(x, y, test_size=0.40, random_state=1) 

# Spliting the 40% subset above into two: one half for cross validation and the other for the test set
x_cv, x_test, y_cv, y_test = train_test_split(x_, y_, test_size=0.50, random_state=1)

# Delete temporary variables
del x_, y_

#### **Feature scaling**

We will use the [`StandardScaler`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) class from scikit-learn. This computes the z-score of your inputs. As a refresher, the z-score is given by the equation:

$$ z = \frac{x - \mu}{\sigma} $$

where $\mu$ is the mean of the feature values and $\sigma$ is the standard deviation.

In [5]:

from sklearn.discriminant_analysis import StandardScaler

# Initialize the class
scaler = StandardScaler()

# Compute the mean and standard deviation of the training set then transform it
X_train_scaled = scaler.fit_transform(x_train)

print(f"Computed mean of the training set: {scaler.mean_.squeeze():.2f}") 
# squeeze() extract value from 1-element array. a=[2] --> a.squeez() = 2
print(f"Computed standard deviation of the training set: {scaler.scale_.squeeze():.2f}")


Computed mean of the training set: 2504.06
Computed standard deviation of the training set: 574.85


#### **Train the model**

For this we will use the [LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) class but take note that there are other [linear regressors](https://scikit-learn.org/stable/modules/classes.html#classical-linear-regressors) which we can also use.

In [6]:
# Initialize the class
from sklearn.linear_model import LinearRegression


linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train_scaled, y_train )

LinearRegression()

#### **Evaluate the Model**### Evaluate the Model

To evaluate the performance of your model, you will measure the error for the training and cross validation sets. For the training error, recall the equation for calculating the mean squared error (MSE):

$$J_{train}(\vec{w}, b) = \frac{1}{2m_{train}}\left[\sum_{i=1}^{m_{train}}(f_{\vec{w},b}(\vec{x}_{train}^{(i)}) - y_{train}^{(i)})^2\right]$$

Scikit-learn also has a built-in [`mean_squared_error()`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html) function that you can use. 

**Note:** Scikit-learn's implementation only divides by `m` and not `2*m`, where `m` is the number of examples.

In [7]:
# Feed the scaled training set and get the predictions
from sklearn.metrics import mean_squared_error


yhat = linear_model.predict(X_train_scaled) 
print(y_train[15:20])
print(yhat[15:20])
print(abs(y_train[15:20]-yhat[15:20]))


# Use scikit-learn's utility function and divide by 2
mse_train = mean_squared_error(y_train, yhat)/2 # scikit-learn's implementation only divides by `m` and not `2*m`
print(f"Training MSE: {mse_train}")

[[738.2 ]
 [540.02]
 [534.58]
 [882.8 ]
 [454.94]]
[[721.24885692]
 [537.29557287]
 [546.97582654]
 [934.24764603]
 [488.88718844]]
[[16.95114308]
 [ 2.72442713]
 [12.39582654]
 [51.44764603]
 [33.94718844]]
Training MSE: 406.1814264310123


####  **MSE for the cross validation set**
(basically the same equation)

$$J_{cv}(\vec{w}, b) = \frac{1}{2m_{cv}}\left[\sum_{i=1}^{m_{cv}}(f_{\vec{w},b}(\vec{x}_{cv}^{(i)}) - y_{cv}^{(i)})^2\right]$$

#### **Scale the cross validation set**

In [8]:
# Scale the cross validation set using the mean and standard deviation of the training set
x_cv_scaled = scaler.transform(x_cv)

print(f"Mean used to scale the CV set: {scaler.mean_.squeeze():.2f}")
print(f"Standard deviation used to scale the CV set: {scaler.scale_.squeeze():.2f}")

Mean used to scale the CV set: 2504.06
Standard deviation used to scale the CV set: 574.85


In [9]:
# Feed the scaled cross validation set
yhat = linear_model.predict(x_cv_scaled)

# Use scikit-learn's utility function and divide by 2
mse_cv=mean_squared_error(y_cv, yhat) / 2
print(f"Cross validation MSE: {mse_train}")

Cross validation MSE: 406.1814264310123


In [10]:
# Instantiate the class to make polynomial features
from sklearn.preprocessing import PolynomialFeatures


poly = PolynomialFeatures(degree=2, include_bias=False)

# Compute the number of features and transform the training set
# x, x^2
x_train_d2 = poly.fit_transform(x_train)


print(x_train[:5])
print(x_train_d2[:5]) # Left column is `x` and right column is `x^2`

[[3324.47]
 [2344.88]
 [3487.73]
 [2630.59]
 [2589.78]]
[[3.32447000e+03 1.10521008e+07]
 [2.34488000e+03 5.49846221e+06]
 [3.48773000e+03 1.21642606e+07]
 [2.63059000e+03 6.92000375e+06]
 [2.58978000e+03 6.70696045e+06]]


#### **Scale x_train_d2**

In [11]:
# Compute the mean and standard deviation of the training set then transform it
x_train_d2_scaled = scaler.fit_transform(x_train_d2)


print(x_train_d2_scaled[:5])

[[ 1.42716085  1.47236975]
 [-0.27690826 -0.36461578]
 [ 1.71116367  1.84024054]
 [ 0.22010538  0.10558969]
 [ 0.14911337  0.03512103]]


#### **Train the model for d=2**

In [12]:
# Train the model
linear_model.fit(x_train_d2_scaled,y_train)

LinearRegression()

In [13]:
# Compute the training MSE
yhat = linear_model.predict(x_train_d2_scaled)
mse_train_d2=mean_squared_error(y_train,yhat)/2

print(f"Training MSE (d = 2): {mse_train_d2}")
print(f"Training MSE (d = 1): {mse_train}")

Training MSE (d = 2): 49.115763074720604
Training MSE (d = 1): 406.1814264310123


### **Choose the best Model**

MSEs are significantly better for both the training and cross validation set when you added the 2nd order polynomial. We can introduce more polynomial terms and see which one gives the best performance. We can have 10 different models like this:<br>
<img align="left" src="images\models.png"    style=" width:480px; padding: 10px;  " /> 

In [14]:
# Initialize lists to save the errors, models, and feature transforms
train_mses_list = []
cv_mses = []
models = []
polys = []
scalers = []

# Loop over 10 times. Each adding one more degree of polynomial higher than the last.
for degree in range(1,11):
    
    # Add polynomial features to the training set
    poly = PolynomialFeatures(degree, include_bias=False)
    X_d_train = poly.fit_transform(x_train)
    polys.append(poly)
    
    # Scale the training set
    scaler=StandardScaler()
    X_d_train_scaled = scaler.fit_transform(X_d_train)
    scalers.append(scaler)
    
    # Create and train the model
    linear_model = LinearRegression()
    linear_model.fit(X_d_train_scaled, y_train )
    models.append(linear_model)
    
    # Compute the training MSE
    yhat = linear_model.predict(X_d_train_scaled)
    train_mse = mean_squared_error(y_train, yhat) / 2
    train_mses_list.append(train_mse)
    
    # Add polynomial features and scale the cross validation set
    X_cv_mapped = poly.transform(x_cv)
    X_cv_mapped_scaled = scaler.transform(X_cv_mapped)
    
    # Compute the cross validation MSE
    yhat = linear_model.predict(X_cv_mapped_scaled)
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    cv_mses.append(cv_mse)

#### **Choose the Best Model**

In [15]:
# Get the model with the lowest CV MSE (add 1 because list indices start at 0)
# This also corresponds to the degree of the polynomial added
print([round(err, 2) for err in cv_mses])
degree = np.argmin(cv_mses) + 1
print(f"Lowest CV MSE is found in the model with degree={degree}")

[551.76, 87.69, 81.14, 79.42, 79.58, 98.74, 99.32, 99.05, 109.59, 121.86]
Lowest CV MSE is found in the model with degree=4


In [16]:
# Add polynomial features to the test set
x_degree_test = polys[degree-1].transform(x_test)

# Scale the test set
X_degree_test_scaled = scalers[degree-1].transform(x_degree_test)

# Compute the test MSE
yhat = models[degree-1].predict(X_degree_test_scaled)
test_mse = mean_squared_error(y_test, yhat) / 2

print(f"Training MSE: {train_mses_list[degree-1]:.2f}")
print(f"Cross Validation MSE: {cv_mses[degree-1]:.2f}")
print(f"Test MSE: {test_mse:.2f}")

Training MSE: 47.15
Cross Validation MSE: 79.42
Test MSE: 104.64


## Neural Networks

The same model selection process can also be used when choosing between different neural network architectures. In this section, you will create the models shown below and apply it to the same regression task above.

<img src='images\nural_net.png' width=350px height=300px>

In [17]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
import time

In [18]:

def build_models():
    
    tf.random.set_seed(20)
    
    model_1 = Sequential(
        [
            Dense(25, activation = 'relu'),
            Dense(15, activation = 'relu'),
            Dense(1, activation = 'linear')
        ],
        name='model_1'
    )

    model_2 = Sequential(
        [
            Dense(20, activation = 'relu'),
            Dense(12, activation = 'relu'),
            Dense(12, activation = 'relu'),
            Dense(20, activation = 'relu'),
            Dense(1, activation = 'linear')
        ],
        name='model_2'
    )

    model_3 = Sequential(
        [
            Dense(32, activation = 'relu'),
            Dense(16, activation = 'relu'),
            Dense(8, activation = 'relu'),
            Dense(4, activation = 'relu'),
            Dense(12, activation = 'relu'),
            Dense(1, activation = 'linear')
        ],
        name='model_3'
    )
    
    model_list = [model_1, model_2, model_3]
    
    return model_list

### **Prepare the Data**

In [19]:
# Add polynomial features
# we are considering degree=1
degree = 1 
poly = PolynomialFeatures(degree, include_bias=False)
X_train_mapped = poly.fit_transform(x_train)
X_cv_mapped = poly.transform(x_cv)
X_test_mapped = poly.transform(x_test)

print(X_train_mapped[:5])

[[3324.47]
 [2344.88]
 [3487.73]
 [2630.59]
 [2589.78]]


#### Scale the features 

In [20]:
scaler = StandardScaler()
X_train_mapped_scaled = scaler.fit_transform(X_train_mapped)
X_cv_mapped_scaled = scaler.transform(X_cv_mapped)
X_test_mapped_scaled = scaler.transform(X_test_mapped)

#### **Choosing the best model**

In [21]:
# Initialize lists that will contain the errors for each model
train_mses_list = []
cv_mses_list = []

# Build the models
models_list = build_models()

# Loop over the the models
for model in models_list:
    
    # Setup the loss and optimizer
    model.compile(
    loss='mse',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
    )

    print(f"Training {model.name}...")
    t=time.time()
    # Train the model
    model.fit(
        X_train_mapped_scaled, y_train,
        epochs=300,
        verbose=0
    )
    t=time.time()-t
    print(f"Done! -->{t}\n")

    
    # Record the training MSEs
    yhat = model.predict(X_train_mapped_scaled)
    train_mse = mean_squared_error(y_train, yhat) / 2
    train_mses_list.append(train_mse)
    
    # Record the cross validation MSEs 
    yhat = model.predict(X_cv_mapped_scaled)
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    cv_mses_list.append(cv_mse)

    
# print results
print("RESULTS:")
for model_num in range(len(train_mses_list)):
    print(
        f"Model {model_num+1}: Training MSE: {train_mses_list[model_num]:.2f}, " +
        f"CV MSE: {cv_mses_list[model_num]:.2f}"
        )

Training model_1...
Done! -->12.59716510772705

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Training model_2...
Done! -->11.7046799659729

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
Training model_3...
Done! -->11.880141973495483

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
RESULTS:
Model 1: Training MSE: 406.18, CV MSE: 551.76
Model 2: Training MSE: 73.40, CV MSE: 112.48
Model 3: Training MSE: 84.97, CV MSE: 132.76


#### Select the model with the lowest CV MSE

In [28]:
# Select the model with the lowest CV MSE
model_num = 2

# Compute the test MSE
yhat = models_list[model_num-1].predict(X_test_mapped_scaled)
test_mse = mean_squared_error(y_test, yhat) / 2

print(f"Selected Model: {model_num}")
print(f"Training MSE: {train_mses_list[model_num-1]:.2f}")
print(f"Cross Validation MSE: {cv_mses_list[model_num-1]:.2f}")
print(f"Test MSE: {test_mse:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
Selected Model: 2
Training MSE: 73.40
Cross Validation MSE: 112.48
Test MSE: 131.76


Let choose Model-3

In [29]:

model_num = 3

# Compute the test MSE
yhat = models_list[model_num-1].predict(X_test_mapped_scaled)
test_mse = mean_squared_error(y_test, yhat) / 2

print(f"Selected Model: {model_num}")
print(f"Training MSE: {train_mses_list[model_num-1]:.2f}")
print(f"Cross Validation MSE: {cv_mses_list[model_num-1]:.2f}")
print(f"Test MSE: {test_mse:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step
Selected Model: 3
Training MSE: 84.97
Cross Validation MSE: 132.76
Test MSE: 134.05
