### **A Three-layer model (Nural Network)**:
* Dense layer with 120 units, relu activation, `kernel_regularizer=tf.keras.regularizers.l2(0.1)`
* Dense layer with 40 units, relu activation, `kernel_regularizer=tf.keras.regularizers.l2(0.1)`
* Dense layer with 6 units and a linear activation. 
Compile using
* loss with `SparseCategoricalCrossentropy`, remember to use  `from_logits=True`
* Adam optimizer with learning rate of 0.01.

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.activations import relu,linear
from keras.losses import SparseCategoricalCrossentropy,MeanSquaredError
from keras.optimizers import Adam
from keras.regularizers import l2


In [2]:
X_train, y_train=np.array([[1],[4],[6],[10],[15],[20]]),np.array([[2],[8],[11],[16],[25],[33]])

In [3]:
model= Sequential(
    [
        ### START CODE HERE ### 
        Dense(units=120,activation='relu',kernel_regularizer=l2(0.1), name='L1'),
        Dense(units=40,activation='relu',kernel_regularizer=l2(0.1),name='L2'),
        Dense(units=1,activation='linear',name='L3'),
        ### START CODE HERE ### 
    ], name= None
)
model.compile(
    ### START CODE HERE ### 
    loss= MeanSquaredError(), # loss function for regression
    #loss=SparseCategoricalCrossentropy(from_logits=True),# loss function for multi-class classification
    optimizer=Adam(0.01),
    ### START CODE HERE ### 
)


#### BEGIN UNIT TEST

In [4]:
# BEGIN UNIT TEST
model.fit(
    X_train, y_train,
    epochs=1000
)
# END UNIT TEST

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 353.4547
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 220.2574
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 133.5183
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 64.0225
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19.8991
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 4.3355
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 19.2697
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 44.4730
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 53.9669
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 44.5348
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 25.8472
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 9.9018
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 3.2140
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 6.2740
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 

In [12]:
predictions = model.predict(X_train)

print(y_train)
predictions=np.round(predictions,decimals=2)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
[[ 2]
 [ 8]
 [11]
 [16]
 [25]
 [33]]
[[ 2.15]
 [ 7.84]
 [10.88]
 [16.41]
 [24.83]
 [33.19]]


In [13]:
X_new = np.array([[7], [12], [25]]) # Example new input data
# The shape is (3, 1) which matches X_train (6, 1) -> (num_samples, num_features)

predictions = model.predict(X_new)

predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[12.259694],
       [19.7735  ],
       [41.54142 ]], dtype=float32)