### Simple nural Network with 1-hidden layer using **'Keras'**

<img src="images/3_layer_nn.png" width="800" height="350">

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input
from keras import Sequential
from keras.losses import MeanSquaredError, BinaryCrossentropy
from keras.activations import sigmoid


In [3]:
x_train = np.array([[-0.79173642, 0.63002953]],dtype=np.float32)  # numpy array         #(size in 1000 square feet)
   

### A Dense layer
A dense layer is essentially a set of weights and biases applied to the input wrapped in an activation function.

We have a single input x and we would apply a weight w and bias b then wrap that in an activation function a giving us..

```a(wx + b)```

depending on how many units / nodes we want our dense layer to have we can just repeat this with different weights & biases giving us

```
[a(w₀x + b₀),
 a(w₁x + b₁), 
 ... 
 a(wₙx + bₙ)]
```

In [4]:
# 1st layer
layer_1 = Dense(units=25, activation = 'sigmoid')
# 2nd Layer
layer_2=Dense(units=15,activation='sigmoid')
# 3rd Layer
layer_3=Dense(units=1,activation='sigmoid')

model=keras.Sequential(
    [layer_1,
     layer_2,
     layer_3,
    ]
)

y=model(x_train)

print(y)

final_output=1 if y>=.5 else 0
print(f'Final output: {final_output}')



tf.Tensor([[0.5554799]], shape=(1, 1), dtype=float32)
Final output: 1


In [5]:
x_train = np.array([[-0.79173642, 0.63002953]],dtype=np.float32)
# 1st layer
layer_1 = Dense(units=25, activation = 'sigmoid')

a1 = layer_1(x_train) # tensorflow_array
print(a1)

# convert tensorflow_array to numpy_array
#np_a1=a1.numpy()
#np_a2=np_a1
'''
print(np_a1)
print(np_a2)
print(np_a1+np_a2)
print(np_a1+a1)
'''

# 2nd Layer
layer_2=Dense(units=15,activation='sigmoid')
a2=layer_2(a1)
print(a2)


# 3rd Layer
layer_3=Dense(units=1,activation='sigmoid')
a3=layer_3(a2)
print(a3)


final_output=1 if a3>=.5 else 0
print(f'Final output: {final_output}')



tf.Tensor(
[[0.5361782  0.5950349  0.6016025  0.5725062  0.52709883 0.47229037
  0.5285002  0.45061257 0.4468955  0.48274004 0.53714126 0.4789966
  0.36532405 0.4092496  0.5204945  0.6278121  0.56388956 0.4538276
  0.4346194  0.52140146 0.51611847 0.4976746  0.50663424 0.43568397
  0.5553992 ]], shape=(1, 25), dtype=float32)
tf.Tensor(
[[0.59307504 0.3705541  0.637739   0.41964647 0.27889356 0.72691655
  0.44232863 0.45560324 0.3814786  0.51116496 0.30576053 0.5952749
  0.64286184 0.498546   0.48019102]], shape=(1, 15), dtype=float32)
tf.Tensor([[0.53974056]], shape=(1, 1), dtype=float32)
Final output: 1


In [6]:
x_train = np.array([[-0.79173642, 0.63002953]],dtype=np.float32)
# 1st layer
layer_1 = Dense(units=25, activation = 'sigmoid')
# 2nd Layer
layer_2=Dense(units=15,activation='sigmoid')
# 3rd Layer
layer_3=Dense(units=1,activation='sigmoid')

model=keras.Sequential(
    [layer_1,
     layer_2,
     layer_3,
    ]
)

y=model(x_train)

print(y)

final_output=1 if y>=.5 else 0
print(f'Final output: {final_output}')



tf.Tensor([[0.39535844]], shape=(1, 1), dtype=float32)
Final output: 0
