## Numpy : Number Python

### Numpy Array Structure:
#### N - dimentional array

<img align="left" src="resources\images\np_array_image.png"    style=" width:780px; padding: 10px;  " /> 

### Importing Library

In [46]:
import numpy as np

### Array Attributes

In [47]:
# 1D array / Vector
a=np.array([1,2,3]) # 1D array / Vector

a

array([1, 2, 3])

In [48]:
# type of the array
type(a)

numpy.ndarray

In [49]:
# shape of the array
a.shape

(3,)

In [50]:
# dimension oof the array
a.ndim

1

In [51]:

a.size # determine how many elements are there in an array

3

In [52]:
a.dtype # print the datatype of the  elements of a
# dtype('int32') because all the elements are int in a. So, all of the elements will treat as int

dtype('int32')

In [53]:
# 2D Array / Matrix
b=np.array([[1,2,3],[4,5,6],[9,8,7],[15,16,17]])

b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9,  8,  7],
       [15, 16, 17]])

In [54]:
b.shape

(4, 3)

In [55]:
b.ndim

2

In [56]:
# 3-D arrays

c = np.array([[[1.0, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]])

d = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
             
             [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [57]:
c

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [58]:
c.dtype # print the datatype of the  elements of c
# dtype('float64') because there is a float element in c. So, all of the elements will treat as float

dtype('float64')

In [59]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [60]:
d.dtype # print the datatype of the  elements of d
# dtype('int32') because all the elements are int in d. So, all of the elements will treat as int

dtype('int32')

In [61]:
c,d # if we want to print both of them

(array([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [62]:
c.shape,d.shape

((1, 3, 3), (2, 3, 3))

In [63]:
c.shape,d.shape

((1, 3, 3), (2, 3, 3))

In [64]:
# array.size determine how many elements are there in an array
a.size, b.size, c.size, d.size 

# For example d has total 118 elements

(3, 12, 9, 18)

In [65]:
# array.nbytes # determine how many bytes consumed by an array
a.nbytes, b.nbytes, c.nbytes, d.nbytes

(12, 48, 72, 72)

### Array Creation

In [66]:
# Array with datatype
array1 = np.array([1, 2, 3],dtype='float') # Array with datatype
array1

array([1., 2., 3.])

In [67]:
# np.zeros((row,column),dtype='datatype')  
# Return an array filled with zeros of given shape and type
zeros=np.zeros((3,4)) # By default all the values will be float
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
# specified dtype = 'int'
zeros=np.zeros((3,3),dtype='int')
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
# Array filled with one
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
# Array filled with any number n
n=10

full=np.full((3,4),n) # By default the values will int

full=np.full((3,4),n,dtype='float')

full

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [71]:
# Indentity array/matrix
identity=np.identity(3)

identity=np.identity(3,dtype='int')

identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [72]:
# Anotherway to create identity matrix
eye=np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
eye=np.eye(4,5,dtype='int')
eye

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [74]:
eye=np.eye(5,5,dtype='int',k=2) # k = 2 -> shift the diagonal 2 position right the main diagonal, 
eye

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [75]:
eye=np.eye(5,4,dtype='int',k=-2) # k = 2 -> shift the diagonal 2 position left the main diagonal, 
eye

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [76]:
# np.arrange will return a vector
arange=np.arange(1,100,5) # Return n=5 spaced values within a given interval.

print(arange)

print(arange[1])
print(arange[-1])

try:
    c = arange[100]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
6
96
The error message you'll see is:
index 100 is out of bounds for axis 0 with size 20


In [77]:
linspace=np.linspace(1,100,50) # will return 50 numbers between 1 to 100
linspace

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [78]:
linspace=np.linspace(1,100,50,dtype='int') # will return 50 numbers between 1 to 100
linspace

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [79]:
# empty array
empty=np.empty((3,5))
empty

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

In [80]:
for i in range(3):
    for j in range(5):
        empty[i,j]=i+j

empty

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

In [81]:
# Array contains random values between 0 and 1
a = np.random.random_sample((4,3))
print(f"np.random.random_sample(4,3): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4,3)    
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.random.random_sample(4,3): a = [[0.42686566 0.93839723 0.49287301]
 [0.02440014 0.4248545  0.26933624]
 [0.89398291 0.78215732 0.07096893]
 [0.88978152 0.70729243 0.37075881]], a shape = (4, 3), a data type = float64
np.random.rand(4): a = [[0.79312229 0.74693939 0.71769592]
 [0.97951648 0.01320295 0.88185288]
 [0.92411458 0.85578066 0.98331058]
 [0.9693382  0.17786863 0.03749576]], a shape = (4, 3), a data type = float64


### Slicing
Slicing creates an array of indices using a set of three values (start:stop:step)

In [82]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [83]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


### Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [85]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2 # b = a^2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


### Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [86]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [87]:
#try a mismatched vector operation
c = np.array([1, 2])
print(c)
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[1 2]
The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


### Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [88]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
b

array([ 5, 10, 15, 20])

### Dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a, b)

print(c)
print(c.dtype)

c = np.dot(b, a)
print(c)


24
int32
24


- `w` will be a 1-dimensional vector of shape (n,).
- we will perform operations by looping through the examples, extracting each example to work on individually by indexing X. For example:`X[i]`
- `X[i]` returns a value of shape (n,), a 1-dimensional vector. Consequently, operations involving `X[i]` are often vector-vector.  

That is a somewhat lengthy explanation, but aligning and understanding the shapes of your operands is important when performing vector operations.

In [95]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(X[1].shape)
print(w.shape)
print(f"c has shape {c.shape}")

(1,)
(1,)
c has shape ()


### Indexing
Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [ ]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2) # -1,2 means it have 2 columns. 
# So 1st row have 2 column, 2nd row have 2 column,... nth row have 2 column
print(a.shape)

#access an element
print(a[2,0]) # 2nd row, 0th column(element)
print(a[2, 0].shape)
print(type(a[2,0]))



#access a row
print(a[2])
print(a[2].shape)
print(type(a[2]))

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]
4
()
<class 'numpy.int32'>
[4 5]
(2,)
<class 'numpy.ndarray'>


In [102]:
a = np.arange(6).reshape(2, -1) # 2,-1 means it have 2 row. 

print(a.shape)

#access an element
print(a[1,2]) # 1st row, 2nd column(element)
print(a[1, 2].shape)
print(type(a[1,2]))



#access a row
print(a[1])
print(a[1].shape)
print(type(a[1]))

(2, 3)
5
()
<class 'numpy.int32'>
[3 4 5]
(3,)
<class 'numpy.ndarray'>
